/* smoke-e2e.js — headless end-to-end check for the 16-ball engine.
   Drives the real P.Game / P.Physics / P.Rules pipeline in Node (no DOM, no
   WebGL). The 3D renderer is stubbed as a no-op so game.js's P.WebGL3D.*
   calls are harmless here; what matters is that state -> physics -> rules ->
   loop runs without throwing. As evidence it emits openable top-down SVG
   snapshots of the logical state (something you can open in a browser).
   Run:  node smoke-e2e.js
   Exits 0 if the full pipeline runs through a break and post-break state. */

var fs = require("fs");

/* Harness convention: `window` is the global object, every module attaches its
   API to window.Poole via a `var W = window` IIFE. No timers in Node. */
globalThis.window = globalThis;
globalThis.requestAnimationFrame = function () { return 0; };
globalThis.setTimeout = function () { return 0; };
globalThis.clearTimeout = function () {};
if (!globalThis.performance) globalThis.performance = {};
globalThis.performance.now = Date.now;

function loadModule(relPath) {
  var code = fs.readFileSync(relPath, "utf8");
  return new Function("window", "globalThis",
    "globalThis.window = globalThis.window || window;\n" + code)(globalThis, globalThis);
}

function fail(msg) { console.log("[FAIL] " + msg); process.exit(1); }
function ok(label) { console.log("[OK] " + label); }

try {
  /* Logic modules only. webgl3d.js is a browser/WebGL module (needs THREE);
     we stub it below so game.js's P.WebGL3D.* calls in Node are no-ops. */
  ["src/config.js", "src/vec.js", "src/ball.js", "src/table.js",
   "src/physics.js", "src/rules.js", "src/player.js", "src/bot.js", "src/ui.js"]
    .forEach(loadModule);

  if (!globalThis.Poole.WebGL3D) {
    globalThis.Poole.WebGL3D = {
      init: function () {},
      resize: function () {},
      draw: function () {},
      pop: function () {},
      screenToTableLogical: function () { return null; }
    };
  }
  loadModule("src/game.js");
} catch (e) { fail("module load threw: " + e.message); }

var P = globalThis.Poole;
var C = P.CONFIG;
var T = P.Table;
var U = P.UI;
var G = P.Game;

/* ---- D7: glint palette headless guard ---------------------------------
   Mirrors webgl3d.js normColor()/hexToRgb01(): every C.BOKEH_PALETTE entry
   must yield a finite [r,g,b] in 0..1. A bad entry produced NaN disc colors
   -> invisible discs -> monochrome black backdrop (D7 follow-up bug). */
{
  var pal = C.BOKEH_PALETTE;
  if (!Array.isArray(pal) || pal.length < 3) fail("C.BOKEH_PALETTE missing or too small");
  function parseHex(entry) {
    var s = String(entry).replace(/^\s*#*/, '');
    if (s.length === 3) s = s[0] + s[0] + s[1] + s[1] + s[2] + s[2];
    if (s.length !== 6) return null;
    var n = parseInt(s, 16);
    if (!isFinite(n) || n < 0) return null;
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  }
  for (var pi = 0; pi < pal.length; pi++) {
    var e = pal[pi], out, rgb;
    if (typeof e === "string") {
      rgb = parseHex(e);
      out = rgb ? [rgb[0] / 255, rgb[1] / 255, rgb[2] / 255] : null;
    } else if (Array.isArray(e) && e.length >= 3) {
      out = [e[0], e[1], e[2]];
    } else {
      out = null;
    }
    var bad = !out;
    for (var cp = 0; cp < 3; cp++) if (!isFinite(out[cp])) bad = true;
    if (bad) {
      fail("C.BOKEH_PALETTE[" + pi + "] " + JSON.stringify(e) +
        " does not parse to a finite [r,g,b] (shader would output NaN -> monochrome backdrop)");
    }
  }
  ok("C.BOKEH_PALETTE: all " + pal.length + " entries parse to finite [r,g,b] in 0..1");
}

/* ---- D7 headless "screen pixels": glint backdrop evaluated as real pixels -----
    Pure-JS port of the backdrop fragment shader (src/webgl3d.js) with uniforms
    generated by the SAME code path as makeBokehFloor() (same constants, same
    random generation). We walk the visible backdrop band at several instants and
    check what a "screen pixel tool" would see: finite colours, the vast majority
    of pixels bright and multicolored well above the near-black 0x0a0c11 field,
    and a non-trivial fraction of pixels actually changing between frames. If this
    passes but the browser still shows a black square, the fault is upstream of the
    shader math (stale page / dead GL pipeline) -> triage ladder B1 (?debug_bg=1). */
{
  var N = Math.max(4, C.BOKEH_COUNT || 24);
  var BOKEH_FALLBACK_RGB = [0.55, 0.65, 1.0];
  function _hx(e) {
    var s = String(e).replace(/^\s*#*/, '');
    if (s.length === 3) s = s[0] + s[0] + s[1] + s[1] + s[2] + s[2];
    if (s.length !== 6) return null;
    var n = parseInt(s, 16);
    if (!isFinite(n) || n < 0) return null;
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  }
  function _col(e) {
    var r = _hx(e), o = null;
    if (r) o = [r[0] / 255, r[1] / 255, r[2] / 255];
    else if (Array.isArray(e) && e.length >= 3) o = [e[0], e[1], e[2]];
    else o = BOKEH_FALLBACK_RGB.slice();
    for (var ci = 0; ci < 3; ci++) if (!isFinite(o[ci])) return BOKEH_FALLBACK_RGB.slice();
    return o;
  }
  /* MUST match makeBokehFloor() exactly: backdropSide = (max-extent + RAIL_DEPTH*16) * 2.2
     (RAIL_DEPTH = 42 in src/webgl3d.js). Disc uv-radius is rLw / side; using the wrong
     side over/under-scales the whole field and breaks the headless "screen pixels" proof. */
  var RAIL_DEPTH_LOCAL = 42;
  var side = (Math.max(C.IX1 - C.IX0, C.IY1 - C.IY0) + RAIL_DEPTH_LOCAL * 16) * 2.2;
  /* Seeded PRNG so the headless "screen pixels" proof is fully reproducible: same
     disc centres/sizes/colours on every run (the real game keeps plain Math.random,
     which varies per load — that variation is also valid, the proof just needs one
     fixed, known-good sample of it). */
  function mulberry32(a) {
    return function() { a |= 0; a = a + 0x6D2B79F5 | 0; var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
  }
  var rnd = mulberry32(20240927);
  var posArr = new Float32Array(N * 2), radArr = new Float32Array(N);
  var colArr = new Float32Array(N * 3), metaArr = new Float32Array(N * 4);
  var palette = C.BOKEH_PALETTE;
  for (var ni = 0; ni < N; ni++) {
    posArr[ni * 2]     = rnd() - 0.5;   /* centred uv: whole plane is -0.5..0.5 */
    posArr[ni * 2 + 1] = rnd() - 0.5;
    var rLw = C.BOKEH_MIN_R + rnd() * (C.BOKEH_VAR_R || 150);
    radArr[ni]         = rLw / side;
    var p = _col(palette ? palette[ni % palette.length] : null);
    var m = 0.45 + rnd() * 0.65;
    colArr[ni * 3]     = p[0] * m; colArr[ni * 3 + 1] = p[1] * m; colArr[ni * 3 + 2] = p[2] * m;
    var spd = (C.BOKEH_SPEED || 0.16) * (0.3 + rnd() * 0.9);
    metaArr[ni * 4]     = rnd() * Math.PI * 2;
    metaArr[ni * 4 + 1] = spd * (rnd() < 0.5 ? -1 : 1);
    metaArr[ni * 4 + 2] = spd * (rnd() < 0.5 ? -1 : 1);
    metaArr[ni * 4 + 3] = 0.4 + rnd() * 0.9;
  }
  /* uniform invariants: nothing can be non-finite or out of range before GL ever sees it */
  for (var vi = 0; vi < N; vi++) {
    var vps = [posArr[vi * 2], posArr[vi * 2 + 1], radArr[vi]];
    for (var vpi = 0; vpi < 3; vpi++) if (!isFinite(vps[vpi])) fail("glint pixels: non-finite uniform slot " +
      (vpi === 0 ? "posX" : vpi === 1 ? "posY" : "rad") + " of disc " + vi);
    if (posArr[vi * 2] < -0.5 || posArr[vi * 2] > 0.5 || posArr[vi * 2 + 1] < -0.5 || posArr[vi * 2 + 1] > 0.5)
      fail("glint pixels: disc " + vi + " centre outside centred uv plane (positions must be -0.5..0.5)");
    for (var vci = 0; vci < 3; vci++) { var cc = colArr[vi * 3 + vci]; if (!isFinite(cc) || cc < 0 || cc > 1.2) fail("glint pixels: bad color " + cc + " disc " + vi); }
    for (var mti = 0; mti < 4; mti++) if (!isFinite(metaArr[vi * 4 + mti])) fail("glint pixels: non-finite meta disc " + vi);
  }
  ok("glint pixels: " + N + " discs with finite, in-range uniforms (centres -0.5..0.5 uv, colours 0..1)");

  var bg = [20 / 255, 35 / 255, 63 / 255];   /* uBg = 0x14233f, same as scene.background */
  var BG_L = 0.299 * bg[0] + 0.587 * bg[1] + 0.114 * bg[2];
  function smooth01(v, a, b) { var t = Math.min(1, Math.max(0, (v - a) / (b - a))); return t * t * (3 - 2 * t); }
  /* JS equivalent of the fragment main(), sampling centred-uv point (cx,cy) at time t.
     Static base camera -> uCamPar = 0; pan/rotation/drift driven exactly as in draw(). */
  function fragPixel(cx, cy, t) {
    var f = C.BOKEH_FLOW || 0.06;
    var x = cx + Math.sin(t * 0.07) * f;
    var y = cy + Math.cos(t * 0.056) * f;
    var uRot = Math.sin(t * (C.BOKEH_ROT_SPEED || 0.25)) * (C.BOKEH_ROT_A || 0.03) +
               Math.cos((t * 1.41 * (C.BOKEH_ROT_SPEED || 0.25)) + 1.37) * (C.BOKEH_ROT_B || 0.018);
    var cr = Math.cos(uRot), sr = Math.sin(uRot);
    var nx = x * cr - y * sr, ny = x * sr + y * cr;
    var outR = bg[0], outG = bg[1], outB = bg[2];
    var dAmp = C.BOKEH_DRIFT || 0.12, coreA = C.BOKEH_CORE_ALPHA || 1.0,
        haloA = C.BOKEH_MID_ALPHA || 0.5, ringA = C.BOKEH_RING_ALPHA || 0.15;
    for (var j = 0; j < N; j++) {
      var ph = metaArr[j * 4];
      var dx = Math.sin(t * metaArr[j * 4 + 1] + ph) * dAmp;
      var dy = Math.cos(t * metaArr[j * 4 + 2] + ph * 1.73) * dAmp;
      var rx = nx - (posArr[j * 2] + dx);
      var ry = ny - (posArr[j * 2 + 1] + dy);
      var rr = Math.max(radArr[j] * (1 + 0.18 * Math.sin(t * metaArr[j * 4 + 3] + ph)), 0.004);
      var tt = Math.sqrt(rx * rx + ry * ry) / rr;
      var core = Math.exp(-tt * tt * 2.6), halo = Math.exp(-tt * tt * 0.75);
      var ring = Math.exp(-Math.pow(tt - 1.1, 2) * 4);
      var w = core * coreA + halo * haloA + ring * ringA;
      outR += colArr[j * 3] * w; outG += colArr[j * 3 + 1] * w; outB += colArr[j * 3 + 2] * w;
    }
    var fall = 0.42 + (1 - 0.42) * (1 - smooth01(Math.sqrt(nx * nx + ny * ny), 0.45, 1.35));
    return [outR * fall, outG * fall, outB * fall];
  }
  function lum(c) { return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]; }
  /* sample the backdrop band the default camera actually sees (~ |c| <= 0.36 uv) at
     three instants: t=0, t=0.5, t=2.0s (drift/pan/rotation all move in this window) */
  var GRID = 41, R = 0.36, times = [0, 0.5, 2];
  function sampleFrame(t) {
    var pxs = [];
    for (var gi = 0; gi < GRID; gi++) {
      var cy = -R + (gi / (GRID - 1)) * 2 * R;
      for (var h = 0; h < GRID; h++) {
        var cx = -R + (h / (GRID - 1)) * 2 * R;
        pxs.push(fragPixel(cx, cy, t));
      }
    }
    return pxs;
  }
  function analyse(pxs, t) {
    var sumL = 0, maxL = -1e9, minL = 1e9, bright = 0, hueful = 0;
    /* post-clamp perceptual metrics: what a screen actually shows (values > 1 clip to 1) */
    var wash = 0, colored = 0, darkGap = 0;
    var Lc = new Array(pxs.length), mR = 0, mG = 0, mB = 0;
    for (var i = 0; i < pxs.length; i++) {
      var p = pxs[i], c;
      for (c = 0; c < 3; c++) if (!isFinite(p[c]) || p[c] < 0) fail("glint pixels: t=" + t + " non-finite/negative channel " + p[c]);
      var L = lum(p);
      sumL += L; maxL = Math.max(maxL, L); minL = Math.min(minL, L);
      mR += p[0]; mG += p[1]; mB += p[2];
      if (L > BG_L + 0.10) bright++;
      var mx = Math.max(p[0], p[1], p[2]), mn = Math.min(p[0], p[1], p[2]);
      if (mx - mn > 0.08) hueful++;
      /* clamp as a GL framebuffer would, then judge what the eye sees */
      var rc = p[0] > 1 ? 1 : p[0], gc = p[1] > 1 ? 1 : p[1], bc = p[2] > 1 ? 1 : p[2];
      var lc = lum([rc, gc, bc]);
      Lc[i] = lc;
      if (Math.min(rc, gc, bc) >= 0.90) wash++;               /* near-white: glint lost its colour */
      var rng = Math.max(rc, gc, bc) - Math.min(rc, gc, bc);
      if (rng >= 0.15 && Math.max(rc, gc, bc) >= 0.35) colored++;
      if (lc <= BG_L + 0.04) darkGap++;
    }
    var p95 = p95of(Lc), p05 = p05of(Lc);
    return { meanL: sumL / pxs.length, maxL: maxL, minL: minL,
              brightFrac: bright / pxs.length, huefulFrac: hueful / pxs.length,
              washFrac: wash / pxs.length, coloredFrac: colored / pxs.length,
              darkGapFrac: darkGap / pxs.length, p95: p95, p05: p05,
              avgRGB: [mR / pxs.length, mG / pxs.length, mB / pxs.length] };
  }
  function p95of(a) { return p95of_(a, 0.95); }
  function p05of(a) { return p95of_(a, 0.05); }
  function p95of_(a, q) {
    var s = a.slice(); s.sort(function (x, y) { return x - y; });
    var idx = Math.floor(q * (s.length - 1));
    return s[idx];
  }
  var a0 = analyse(sampleFrame(times[0]), times[0]);
  var a1 = analyse(sampleFrame(times[1]), times[1]);
  var a2 = analyse(sampleFrame(times[2]), times[2]);
  if (process.env.GLINT_DEBUG === "1") {
    var fa = sampleFrame(times[0]), fb = sampleFrame(times[2]);
    var movedD = 0;
    for (var md = 0; md < fa.length; md++) if (Math.abs(lum(fa[md]) - lum(fb[md])) > 0.02) movedD++;
    console.log("glint DEBUG @t=0 meanL=" + a0.meanL.toFixed(3) + ", maxL=" + a0.maxL.toFixed(3) +
      " bright=" + (a0.brightFrac * 100).toFixed(1) + "% hueful=" + (a0.huefulFrac * 100).toFixed(1) +
      "% wash=" + (a0.washFrac * 100).toFixed(1) + "% colored=" + (a0.coloredFrac * 100).toFixed(1) +
      "% darkGap=" + (a0.darkGapFrac * 100).toFixed(1) + "% p95L=" + a0.p95.toFixed(3) +
      " p05L=" + a0.p05.toFixed(3) + ", @t=2.0 bright=" + (a2.brightFrac * 100).toFixed(1) +
      "% hueful=" + (a2.huefulFrac * 100).toFixed(1) +
      "% moving=" + ((movedD / fa.length) * 100).toFixed(1) + "%");
  }
  if (a0.meanL <= BG_L + 0.03) fail("glint pixels: backdrop reads as the black field itself " +
    "mean luminance " + a0.meanL.toFixed(4) + " vs background " + BG_L.toFixed(4));
  if (a0.brightFrac < 0.28) fail("glint pixels: only " + Math.round(a0.brightFrac * 100) +
    "% of the visible band is lit above bg+0.10 -> disc field too sparse (centres/radii bug?)");
  if (a0.huefulFrac < 0.15) fail("glint pixels: only " + Math.round(a0.huefulFrac * 100) +
    "% of pixels are hue-variant -> not multicolored");
   /* Perceptual guards (post-clip, i.e. what the screen actually shows). Calibrated against the
      fixed-seed field of soft out-of-focus bokeh orbs on dark ground. The guards only catch real
      regressions: a black square (unlit), a monochrome/grey wash, or a saturated white field
      that loses colour. */
  if (a0.washFrac > 0.25) fail("glint pixels: " + Math.round(a0.washFrac * 100) +
    "% of band is near-white after clipping -> glints clip to pure white and lose their hue; lower CORE/MID/RING or shrink discs");
  if (a0.coloredFrac < 0.12) fail("glint pixels: only " + Math.round(a0.coloredFrac * 100) +
    "% of band reads as real colour (channel spread >= 0.15 at value >= 0.35) -> field too dim or washed to grey");
   if (a0.darkGapFrac < 0.12) fail("glint pixels: only " + Math.round(a0.darkGapFrac * 100) +
     "% of band is dark ground -> bokeh orbs too dense/large, field reads as a solid wash instead of shimmering orbs");
  if (a2.meanL <= BG_L + 0.03 || a2.brightFrac < 0.28) fail("glint pixels: field darkened at t=" + times[2] +
    " (drift/rotation must not push the whole field out of view)");
  /* animation: between t=0 and t=2.0s a meaningful share of pixels must visibly move */
  var fa = sampleFrame(times[0]), fb = sampleFrame(times[2]);
  var moved = 0;
  for (var mi = 0; mi < fa.length; mi++) if (Math.abs(lum(fa[mi]) - lum(fb[mi])) > 0.02) moved++;
  var moveFrac = moved / fa.length;
  if (moveFrac < 0.15) fail("glint pixels: field static between t=0 and t=2s (" +
    Math.round(moveFrac * 100) + "% of pixels changed > 0.02 luminance)");
  if (process.env.GLINT_DEBUG === "1") {
    console.log("glint DEBUG @t=0 meanL=" + a0.meanL.toFixed(3) + ", maxL=" + a0.maxL.toFixed(3) +
      " bright=" + (a0.brightFrac * 100).toFixed(1) + "% hueful=" + (a0.huefulFrac * 100).toFixed(1) +
      "% wash=" + (a0.washFrac * 100).toFixed(1) + "% colored=" + (a0.coloredFrac * 100).toFixed(1) +
      "% darkGap=" + (a0.darkGapFrac * 100).toFixed(1) + "% p95L=" + a0.p95.toFixed(3) +
      " p05L=" + a0.p05.toFixed(3) + ", @t=2.0 bright=" + (a2.brightFrac * 100).toFixed(1) +
      "% hueful=" + (a2.huefulFrac * 100).toFixed(1) + "% moving=" + (moveFrac * 100).toFixed(1) + "%");
  }
  ok("glint pixels @t=0: meanL=" + a0.meanL.toFixed(3) + ", bright=" + Math.round(a0.brightFrac * 100) +
     "%, hueful=" + Math.round(a0.huefulFrac * 100) + "% | wash=" + Math.round(a0.washFrac * 100) +
     "%, colored=" + Math.round(a0.coloredFrac * 100) + "%, darkGap=" + Math.round(a0.darkGapFrac * 100) +
     "%, p95L=" + a0.p95.toFixed(3) + ", p05L=" + a0.p05.toFixed(3) +
     " | @t=2.0s: meanL=" + a2.meanL.toFixed(3) + ", bright=" + Math.round(a2.brightFrac * 100) +
     "% | moving=" + Math.round(moveFrac * 100) + "%");
}

/* Table transform for the SVG snapshots (headless: we only need the mapping). */
T.fit({ width: 0, height: 0 }, 1600, 900);
var W = 1600, H = 900;

/* ---- seed + smoke-drive ---------------------------------------------
   The renderer is a headless no-op, so we assert the loop *doesn't throw* and
   that state evolves, not on pixel output. */
try { G.newGame(); } catch (e) { fail("P.Game.newGame() threw: " + e.message); }
var state = globalThis.Poole.State();
if (!state) fail("P.State() returned null after newGame");
if (state.balls.length !== 16) fail("expected 16 balls, got " + state.balls.length);
ok("newGame: 16 balls on table, phase=" + state.phase + ", turn=human");

for (var f = 0; f < 50; f++) { G.tick(); }   /* must not throw */
ok("50 idle frames ran without throwing");

/* ---- I1: power adjustability guard (drag -> power -> shot speed) ------------
   Drives the real exported UI flow (startAim / endAim) with headless logical
   coords, so a regression in the drag->power mapping or the reversed-aim sign
   would fail before it reaches the browser. Power must ramp monotonically from
   0 to full (clamped at C.POWER_MAX_DIST) and buildShot() must fire AWAY from
   the pointer at a speed inside [120, MAX_SHOT_SPEED]. */
{
  U.shootable = true;
  var cue = state.cue;
  var drags = [C.MIN_DRAG + 1, C.POWER_MAX_DIST * 0.5, C.POWER_MAX_DIST, C.POWER_MAX_DIST + 60];
  var powers = [];
  for (var dgi = 0; dgi < drags.length; dgi++) {
    U.startAim({ x: cue.x + drags[dgi], y: cue.y });
    powers.push(U.power);
  }
  U.aiming = false;
  var rampOk = true;
  for (var rgi = 1; rgi < powers.length; rgi++) {
    if (!(isFinite(powers[rgi]) || powers[rgi] >= 0)) fail("I1 guard: power not finite at drag " + drags[rgi]);
    if (powers[rgi] < 0 || powers[rgi] > 1) fail("I1 guard: power out of [0,1] at drag " + drags[rgi]);
    if (powers[rgi] < powers[rgi - 1] - 1e-9) fail("I1 guard: power not monotonic with drag distance");
  }
  if (!(powers[powers.length - 2] >= 0.99)) fail("I1 guard: power does not reach ~1.0 at C.POWER_MAX_DIST");
  var fired = null, origOnFire = P.UI.onFire;   /* restore the real onHumanFire when this I1 stub ends */
  var origOnFire = P.UI.onFire;   /* I1's stub must not outlive the guard: restore below */
  U.onFire = function (s) { fired = s; };
  U.startAim({ x: cue.x + (C.POWER_MAX_DIST + 60), y: cue.y - 12 });
  U.endAim();
  if (!fired) fail("I1 guard: endAim never emitted a shot via onFire");
  var sx = fired.vx, sy = fired.vy;
  if (!isFinite(sx) || !isFinite(sy)) fail("I1 guard: non-finite shot velocity " + JSON.stringify(fired));
  var offX = U.aimX - cue.x, offY = U.aimY - cue.y;
  var od = Math.sqrt(offX * offX + offY * offY) || 1;
  /* reversed-aim convention: velocity must point AWAY from the pointer, i.e.
     its dot product with -normalized(pointer - cue) is ~1 */
  var aligned = (sx * (-offX / od) + sy * (-offY / od));
  if (aligned < 0.98) fail("I1 guard: shot direction wrong (" + aligned.toFixed(3) + ")");
  var spd = Math.sqrt(sx * sx + sy * sy);
  if (spd < 120 - 1e-6 || spd > C.MAX_SHOT_SPEED + 1e-6) {
    fail("I1 guard: shot speed " + spd.toFixed(1) + " outside [120, " + C.MAX_SHOT_SPEED + "]");
  }
  U.onFire = origOnFire;   /* restore the real onHumanFire so the break shot below actually fires */
  ok("I1 power: monotonic drag->power ramp, full at C.POWER_MAX_DIST, reversed-aim direction and top-end speed correct");
}

function SC(x, y) { return { x: T.offX + x * T.size, y: T.offY + y * T.size }; }
var onTable = 0;
state.balls.forEach(function (b) {
  var s = SC(b.x, b.y);
  if (!isFinite(s.x) || !isFinite(s.y)) fail("non-finite ball " + b.id + ": " + JSON.stringify({ x: b.x, y: b.y }));
  if (!b.inPocket) onTable++;
});
emitSVG("snapshot-rack.svg", state, false);
ok("snapshot-rack.svg emitted; " + onTable + "/" + state.balls.length + " balls on table");

/* ---- aim + fire the break ------------------------------------------- */
U.aiming = true; U.shootable = true; U.power = 0.65;
U.aimX = state.cue.x - 220; U.aimY = state.cue.y + 180;
emitSVG("snapshot-aim.svg", state, true);     /* rack + cue stick + dash line */

/* Reversed-aim convention (ui.js): the cue flies AWAY from the pointer. */
U.onFire({ vx: 45, vy: -C.MAX_SHOT_SPEED * 0.82 });
var settled = 0, MAX_FRAMES = 8000;
while (state.shotInFlight && settled < MAX_FRAMES) { G.tick(); settled++; }
if (state.shotInFlight) fail("break shot never settled in " + MAX_FRAMES + " frames");
ok("break settled in " + settled + " frames; phase=" + state.phase);

emitSVG("snapshot-after.svg", state, false);
var onTable2 = 0; state.balls.forEach(function (b) { if (!b.inPocket) onTable2++; });
ok("post-break: " + onTable2 + " balls still on table");

/* ---- extra showable frames (top-down schematic) -------------------------
   Exercise state paths the break scene never covers: a game-over flag (DOM
   #gameover overlay) and a freshly re-spotted cue (foul). */

/* (A) clean win by "You": 8-ball pocketed + gameOver -> overlay. */
{
  var stW = globalThis.Poole.State();
  for (var wi = 0; wi < stW.balls.length; wi++) { if (stW.balls[wi].id === 8) { stW.balls[wi].inPocket = true; } }
  stW.gameOver = true;
  stW.winner = stW.players[0];                        /* "You" */
  stW.message = stW.winner.name + " wins! Click to play again.";
  emitSVG("snapshot-win.svg", stW, false, true);      /* 4th arg = overlay on */
}

/* (B) scratch foul: fresh full rack, cue re-spotted to centre. */
{
  G.newGame();                                        /* pristine 16-ball state */
  var stF = globalThis.Poole.State();
  if (stF.cue) { stF.cue.x = C.CENTER.x; stF.cue.y = C.CENTER.y; }
  stF.message = "SCRATCH - foul (cue back to centre)";
  emitSVG("snapshot-foul.svg", stF, false);
}

var files = ["snapshot-rack.svg", "snapshot-aim.svg", "snapshot-after.svg", "snapshot-win.svg", "snapshot-foul.svg"];
for (var a = 0; a < files.length; a++) {
  ok(files[a] + " (" + fs.statSync(files[a]).size + " bytes)");
}
console.log("\nSnapshots written to repo root. Open a .svg file in any browser.");

/* ---- top-down SVG snapshot (logical coords). Pure Node, no canvas. ----
   Renders the current state's balls/rack/rail as an openable <svg>. `st` is
   the specific state object to snapshot. */
function emitSVG(path, st, withAim, showOverlay) {
  var size = T.size, ox = T.offX, oy = T.offY;
  function sc(lx, ly) { return { x: ox + lx * size, y: oy + ly * size }; }
  var r = C.BR * size, pr = C.POCKET_R * size;
  var o = ['<svg xmlns="http://www.w3.org/2000/svg" width="' + W + '" height="' + H + '" viewBox="0 0 ' + W + ' ' + H + '">'];
  o.push('<defs>' +
    '<radialGradient id="shine" cx="0.30" cy="0.28" r="1">' +
    '<stop offset="0" stop-color="#ffffff"/><stop offset="0.2" stop-color="#ffffff" stop-opacity="0.9"/>' +
    '<stop offset="0.7" stop-color="#ffffff" stop-opacity="0.06"/><stop offset="1" stop-color="#ffffff" stop-opacity="0"/></radialGradient>' +
    '<linearGradient id="felt" x1="0" y1="0" x2="0" y2="1">' +
    '<stop offset="0" stop-color="#0e6b3c"/><stop offset="0.5" stop-color="#147a4a"/><stop offset="1" stop-color="#0f6d3d"/></linearGradient>' +
    '<radialGradient id="pocket" cx="0.5" cy="0.5" r="0.75">' +
    '<stop offset="0" stop-color="#020704"/><stop offset="0.6" stop-color="#11190f"/><stop offset="1" stop-color="#2a1d0e"/></radialGradient>' +
    '</defs>');

  o.push('<rect x="0" y="0" width="' + W + '" height="' + H + '" fill="#0b0e12"/>');
  var left = ox + C.IX0 * size, up = oy + C.IY0 * size, right = ox + C.IX1 * size, down = oy + C.IY1 * size;
  o.push('<rect x="' + left + '" y="' + up + '" width="' + (right - left) + '" height="' + (down - up) + '" fill="url(#felt)"/>');

  /* dark wood frame + light highlight border */
  o.push('<rect x="' + (ox + (C.IX0 + 17) * size) + '" y="' + (oy + (C.IY0 + 17) * size) + '" width="' + (C.IX1 - C.IX0 - 34) * size +
    '" height="' + (C.IY1 - C.IY0 - 34) * size + '" fill="none" stroke="#2e1608" stroke-width="' + r + '"/>');
  o.push('<rect x="' + (ox + (C.IX0 + 1) * size) + '" y="' + (oy + (C.IY0 + 1) * size) + '" width="' + (C.IX1 - C.IX0 - 2) * size +
    '" height="' + (C.IY1 - C.IY0 - 2) * size + '" fill="none" stroke="#ffffff3d" stroke-width="' + (r * 0.35).toFixed(1) + '"/>');

  for (var gi = 0; gi < 8; gi++) {
    var gx = ox + (C.IX0 + C.BR * (3 + gi * 12)) * size;
    o.push('<line x1="' + gx + '" y1="' + up + '" x2="' + gx + '" y2="' + down + '" stroke="#ffffff05" stroke-width="' + (r * 0.6).toFixed(1) + '"/>');
  }

  for (var i = 0; i < C.pockets.length; i++) {
    var p = sc(C.pockets[i].x, C.pockets[i].y);
    o.push('<circle cx="' + p.x + '" cy="' + p.y + '" r="' + pr + '" fill="url(#pocket)"/>');
    o.push('<circle cx="' + p.x + '" cy="' + p.y + '" r="' + (pr * 0.65).toFixed(1) + '" fill="#050704" opacity="0.5"/>');
  }

  st.balls.forEach(function (b) {
    if (b.inPocket) return;
    var s = sc(b.x, b.y);
    var hex = b.color || "#f0f0f0";
    o.push('<circle cx="' + s.x + '" cy="' + s.y + '" r="' + r + '" fill="' + hex + '"/>');
    o.push('<circle cx="' + s.x + '" cy="' + s.y + '" r="' + r + '" fill="url(#shine)" opacity="0.92"/>');

    if (typeof b.id === "number" && b.id >= 9 && b.id <= 15) {
      o.push('<ellipse cx="' + s.x + '" cy="' + s.y + '" rx="' + (r * 0.74).toFixed(1) + '" ry="' + (r * 0.32).toFixed(1) + '" fill="#ffffffcc"/>');
    }
    if (typeof b.id === "number") {
      var nfill = (b.id === 8) ? "#ddd" : "#fff";
      o.push('<text x="' + (s.x + r * 0.12).toFixed(1) + '" y="' + (s.y + r * 0.15).toFixed(1) +
        '" font-family="Arial,sans-serif" font-size="' + (r * 0.6).toFixed(1) + '" font-weight="bold"' +
        ' text-anchor="middle" dominant-baseline="central" fill="' + nfill + '">' + b.id + '</text>');
    } else if (b.id === "cue") {
      var d = r * 0.27;
      o.push('<circle cx="' + s.x + '" cy="' + (s.y - d).toFixed(1) + '" r="' + d.toFixed(1) + '" fill="#777"/>');
      o.push('<circle cx="' + (s.x - d).toFixed(1) + '" cy="' + (s.y + d * 0.6).toFixed(1) + '" r="' + d.toFixed(1) + '" fill="#777"/>');
      o.push('<circle cx="' + (s.x + d).toFixed(1) + '" cy="' + (s.y + d * 0.6).toFixed(1) + '" r="' + d.toFixed(1) + '" fill="#777"/>');
    }
  });

  if (withAim) {
    var cu = st.cue;
    var dx = U.aimX - cu.x, dy = U.aimY - cu.y;
    var dl = Math.sqrt(dx * dx + dy * dy) || 1;
    var dirx = -(dx / dl), diry = -(dy / dl);   /* real shot direction (away from pointer) */
    var ls = sc(cu.x + dirx * (C.BR + 46), cu.y + diry * (C.BR + 46));
    var le = sc(cu.x + dirx * 470, cu.y + diry * 470);
    o.push('<line x1="' + ls.x + '" y1="' + ls.y + '" x2="' + le.x + '" y2="' + le.y +
      '" stroke="#5ed7ff" stroke-opacity="0.6" stroke-width="' + (r * 0.8).toFixed(1) + ' stroke-dasharray="14,14"/>');
    o.push('<circle cx="' + le.x + '" cy="' + le.y + '" r="' + ((C.BR + C.BR * 0.35) * size).toFixed(1) +
      '" fill="none" stroke="#5ed7ff" stroke-width="' + (r * 0.3).toFixed(1) + '" opacity="0.6"/>');

    var tip = sc(cu.x + dirx * (42 + C.BR), cu.y + diry * (42 + C.BR));
    var butt = sc(cu.x - dirx * 380, cu.y - diry * 380);
    o.push('<line x1="' + tip.x + '" y1="' + tip.y + '" x2="' + butt.x + '" y2="' + butt.y +
      '" stroke="#c59a63" stroke-width="' + (r * 1.7).toFixed(1) + '" stroke-linecap="round" opacity="0.9"/>');
    o.push('<line x1="' + tip.x + '" y1="' + tip.y + '" x2="' + butt.x + '" y2="' + butt.y +
      '" stroke="#6b4221" stroke-width="' + (r * 0.5).toFixed(1) + '" stroke-linecap="round" opacity="0.35"/>');
    o.push('<circle cx="' + tip.x + '" cy="' + tip.y + '" r="' + (r * 0.6).toFixed(1) + '" fill="#7e8b95"/>');
  }

  if (showOverlay) {
    /* Full-screen game-over overlay (screen coords) — mirrors the DOM #gameover
       centre card, shown only while state.gameOver. */
    var minDim = Math.min(W, H);
    var fs1 = Math.round(minDim * 0.07), fs2 = Math.round(minDim * 0.04);
    o.push('<rect x="0" y="0" width="' + W + '" height="' + H + '" fill="#000" opacity="0.5"/>');
    var winName = st.winner ? st.winner.name : "?";
    o.push('<text x="' + (W / 2) + '" y="' + (H / 2 - minDim * 0.03).toFixed(1) + '" ' +
      'text-anchor="middle" font-family="Arial,sans-serif" font-weight="bold" ' +
      'font-size="' + fs1 + '" fill="#ffffff">' + escapeXml("Game over - " + winName + " wins!") + '</text>');
    o.push('<text x="' + (W / 2) + '" y="' + (H / 2 + minDim * 0.06).toFixed(1) + '" ' +
      'text-anchor="middle" font-family="Arial,sans-serif" font-weight="bold" ' +
      'font-size="' + fs2 + '" fill="#ffffff">' + escapeXml("Click the table to play again") + '</text>');
  }

  o.push('<text x="' + W / 2 + '" y="' + (H - 8) + '" font-family="Arial" font-size="14" ' +
    'fill="#9fd7ff" text-anchor="middle">' + escapeXml(st.message || "") + '</text>');

  o.push('</svg>');
  fs.writeFileSync(path, o.join(""), "utf8");
}

function escapeXml(s) {
  return String(s).replace(/[&<>"']/g, function (ch) {
    switch (ch) { case "&": return "&amp;"; case "<": return "&lt;"; case ">": return "&gt;";
                  case '"': return '&quot;'; case "'": return "&#39;"; }
  });
}
